artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  #source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  #source_URL: https://github.com/entbappy/Branching-tutorial/blob/master/Chicken-fecal-images.zip
  #source_URL: https://raw.githubusercontent.com/entbappy/Branching-tutorial/master/Chicken-fecal-images.zip
  #source_URL: https://github.com/Sujata2017/Chicken-Disease-Classification/blob/main/Chicken-fecal-images.zip
  #source_URL: https://github.com/Sujata2017/Chicken-Disease-Classification/blob/main/Chicken-fecal-images.7z
  source_URL: https://github.com/Sujata2017/Chicken-Disease-Classification/blob/main/Chicken-fecal-images.zip

  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion